tap "caskroom/cask"
tap "caskroom/versions"
tap "homebrew/bundle"
tap "homebrew/versions"

brew "bash"
brew "bash-completion"
brew "chruby"
brew "fzf"
brew "git"
brew "neovim/neovim/neovim"
brew "postgresql"
brew "ruby-install"

cask "adium"
cask "android-studio"
cask "dropbox"
cask "firefox"
cask "google-chrome"
cask "google-drive"
cask "iterm2-beta"
cask "macpass"
cask "slack"
cask "spotify"
cask "stremio"

